typography_spectrum: 0.2252268404699862
content_rating:
  adult: true
color:
  brandStrength: 0.7812926322221756
  lightness: 0.5496921881567687
  saturation: 0.9925383892841637
  rhythmicContrast: 0.34439157461747527
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
opengraph:
  appId: babetones
layout_spectrum: 0.2530270873103291
author:
  name: Jonathan Wilson
  email: jontheoptimist@gmail.com
  url: www.babetones.com
name: BABE
title: Ether/Ore
